### POST request to register a user
POST http://localhost:3000/auth/register
Content-Type: application/json

{
  "email": "bezylmophatotieno@gmail.com",
  "password": "123456789"
}
###


### POST request to login a user
POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "email": "bezylmophatotieno@gmail.com",
  "password": "123456789"
}
###
