### POST request to register a user
POST https://my-portfolio-2025-byihznatm-bezylmophatotienos-projects.vercel.app/auth/register
Content-Type: application/json

{
  "email": "bezylmophatotieno@gmail.com",
  "password": "123456789"
}
###


### POST request to login a user
POST https://my-portfolio-2025-byihznatm-bezylmophatotienos-projects.vercel.app//auth/login
Content-Type: application/json

{
  "email": "bezylmophatotieno@gmail.com",
  "password": "123456789"
}
###
